# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/haydn/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),haydn)

$(call add-radio-file-sha1-checked,radio/abl.img,12380ff05783ec689c49b6ab5dcba61d51e55023)
$(call add-radio-file-sha1-checked,radio/aop.img,f563656ba3959790568c39031c9e2a284d1b2c8b)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,ea3e83c392191f6311e4e1f3273978f1966797ab)
$(call add-radio-file-sha1-checked,radio/cpucp.img,0e3e5d956adc4fc269ed0c7a292bdda845f6817f)
$(call add-radio-file-sha1-checked,radio/devcfg.img,735383d5ecbd8e82a6456c5a6fcb21a4d7de4ee4)
$(call add-radio-file-sha1-checked,radio/dsp.img,453413b40e59bfbd20bcb03dce4e3538f0f04550)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b9906e55d16137e8cfd1b0edf6e0ac7eff6f0ab8)
$(call add-radio-file-sha1-checked,radio/hyp.img,0d7162db595deabca911f0339e9246c8a557d1a6)
$(call add-radio-file-sha1-checked,radio/imagefv.img,10ddd77d16a84e806a6776b0215ed4cdeb3e7602)
$(call add-radio-file-sha1-checked,radio/keymaster.img,3bc3d8b0611bf2d20446fd80d8a8b0b77398745a)
$(call add-radio-file-sha1-checked,radio/modem.img,2c3eceaba0d29fd4662ff2a1e920b8866a0045ab)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2bf5d0a50eaf9211b68b274bb057b74234103c77)
$(call add-radio-file-sha1-checked,radio/shrm.img,3f25fc15d098f31527398cc09c91636f6e91903c)
$(call add-radio-file-sha1-checked,radio/tz.img,1432b4ad22b1354bef7f53af68bcace9247e65fa)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,cde39c35884e13ed507502fa5e7e53e8280e06f8)
$(call add-radio-file-sha1-checked,radio/xbl.img,a9d7e58e674e1d341c570fb9b958b7096c90c450)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,0b154e0790e1b90e9d9dee2f90e68da05a6b6776)

endif
